### ISSUE TITLE
Possible issue with Windows 11

### ISSUE THREAD

**Issue by rentalanimal** [RenePotocnik/RecRoom-Shirt-Printer#1]
I've been using the printer on my work PC (Windows 10) and my home PC (Windows 11). The home PC adds a cycle of unnecessary text selection (between 5 and 8) in between each line submission. This adds substation time to the process. Not sure what I can do to make the cursor not do that. I've calibrated the home monitor as well even though it is 16:9.

**Comment by dukedotdev** [comment]
I've got the same issue here, looked at it and it seems to think that your paste is failing. For a bandaid fix just go to importing.py, go to line 108, and set the 10 to 1, to be extra safe you can do the same on line 123. Just to note though, this will disable all checks, if it seems to fail to paste I'd just wait for an actual fix. I'd fix the issue myself but it's 2 AM and I'm not great at Python :P

**Comment by dukedotdev** [comment]
Ok, looked at it a bit more and I've found that the error is the if at 112, might be because RR added a new toggle, Room Owner Lock, causing it to check the wrong place and return false until it times out. No clue how any of this works though, so I'll leave McRen to fix it.

**Comment by RenePotocnik** [comment]
In the new update the position of the *Value* input changed. 
You can get fix it by calibrating the positions - https://github.com/RenePotocnik/RecRoom-Shirt-Printer#prepare-for-successful-calibration

In the mean time I'll update the the default coordinates ☕
